
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/
    suffix: .html
    cache: false

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000

server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:xml/*.xml

whitePaths: /user/login;/;/favicon.ico;/index.html;/static/index.html;/user/addUser

#邮件，邮件需要设置什么第三端登陆协议
email:
  username:
  password:
  mailIp: smtp.exmail.qq.com
  mailPort: 465
